title: Nilakshan Kunananthaseelan
name: Nilakshan Kunananthaseelan
description: The research portfolio of Nilakshan Kunananthaseelan, an AI researcher based in Melbourne.
url: "https://nilakshankunananthaseelan.github.io"
baseurl: ""
lang: en-AU
timezone: Australia/Melbourne

author:
  name: Nilakshan Kunananthaseelan
  email: nilakjhc@gmail.com
  location: Melbourne, Australia

permalink: /writing/:title/

collections:
  papers:
    output: true
    permalink: /papers/:name/

defaults:
  - scope:
      path: ""
      type: papers
    values:
      layout: paper

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

sass:
  style: compressed

plugins:
  - jekyll-sitemap

exclude:
  - .bundle
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - _make_favicon.sh
  - _make_thumbnails.sh
